### PR TITLE
Is it possible to customize deck name?

### PR DESCRIPTION
**Pull request by omgfrost**
as title says along with the static Class name if a full code is provided like this:
```
### Thijs Tempo Priest
# Class: Priest
# Format: Standard
# Year of the Phoenix
#
# 2x (1) Disciple of Galakrond
# 1x (1) Imprisoned Homunculus
# 2x (1) Renew
# 2x (2) Imprisoned Vilefiend
# 2x (2) Penance
# 2x (2) Sethekk Veilweaver
# 1x (2) Shadow Word: Death
# 2x (3) Apotheosis
# 1x (3) Mindflayer Kaahrj
# 2x (4) Escaped Manasaber
# 2x (4) Grave Rune
# 2x (4) Holy Nova
# 2x (5) Psyche Split
# 2x (5) Time Rip
# 1x (6) Kronx Dragonhoof
# 1x (7) Galakrond, the Unspeakable
# 1x (7) Skeletal Dragon
# 1x (7) Soul Mirror
# 1x (8) Murozond the Infinite
#
AAECAa0GCNMKha0DjrED47QDsLoDyL4DyMAD2MIDC8kGmakD2awD2qwDza8DhLYDk7oDlroDm7oDr7oD9LsDAA==
#
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
# Generated by HDT - https://hsreplay.net
```
Thanks in advance

### CODE REVIEW

**Comment by oliverfei** [comment]
Done. As a sidenote, PRs are for requesting to merge new code into the repo. For feature requests, inquiries, and bug reporting, issues should be raised instead.

**Comment by omgfrost** [comment]
Ok sorry. I'll do that next time
Thanks,

**Comment by omgfrost** [comment]
Hmmm...just tried with above code and it doesnt add any deck even, in the site

**Comment by oliverfei** [comment]
Did you clear the cache and refresh?

**Comment by omgfrost** [comment]
ok now its working! Perfect! i did ctrl+f5 and it worked. But i know i had to do that so i did the key combo even first time (?)
Anyway it's solved. Thanks so much

**Pull request closed without merging**
